### ISSUE TITLE
Kotlin and Arrow: the functional way

### ISSUE THREAD

**Issue by nluaces** [arrow-kt/arrow-media#13]
**Type of Content:** Video

**Link:** https://thoughtworks.wistia.com/medias/ifra1gzrho

**Brief Description of Content:** Talk about Kotlin and how Arrow library completes it in order to follow a pure functional way.

**Author/Presenter Name:** Noe Luaces

**Twitter handle:** noe_luaces

**Comment by calvellido** [comment]
Closed through #16
