### ISSUE TITLE
[Add Media] Effect polymorphism with Arrow FX

### ISSUE THREAD

**Issue by colomboe** [arrow-kt/arrow-media#14]
**Type of Content:** blog post

**Link:** https://www.msec.it/blog/effect-polymorphism-with-arrow-fx/

**Brief Description of Content:** Wonder how to handle side effects in a very clean way while abstracting the real effect implementation? #Arrow #FX provides an easy way to do this, without the burden of Higher-Kinded Types.

**Author/Presenter Name:** Emanuele Colombo

**Twitter handle:** https://twitter.com/colomboe/status/1151815338708930561

**Comment by MaureenElsberry** [comment]
Closing this out as it was already added to media.
