### ISSUE TITLE
[Add Media] Tech talk about Arrow at All Things Open, 2020 conference

### ISSUE THREAD

**Issue by overfullstack** [arrow-kt/arrow-media#43]
**Type of Content:** 
Tech talk

**Link:** 
https://www.youtube.com/watch?v=Dvr6gx4XaD8&list=PLrJbJ9wDl9EC0bG6y9fyDylcfmB_lT_Or

**Brief Description of Content:**
A Metric-driven approach to reduce Cognitive Complexity in a code base, using Functional Programming, demoed **hands-on**, by solving a complex real-world ubiquitous design challenge - REST API Bulk Request Validation, with an extensible Framework that separates what-to-do (Validations) from how-to-do (Validation Orchestration). Let's do a case study of a successful implementation done by our team in the world's largest SaaS org, _Salesforce_, using Kotlin and Arrow.

**Author/Presenter Name:**
Gopal S Akshintala

**Twitter handle:**
@GopalAkshintala

**Comment by MaureenElsberry** [comment]
Added with PR #44 - Thanks, Gopal!
