### ISSUE TITLE
Third article in the 'FP for Enterprise Bee' series

### ISSUE THREAD

**Issue by garthgilmour** [arrow-kt/arrow-media#49]
Article on GDG Medium Publication

https://medium.com/google-developer-experts/advanced-fp-for-the-enterprise-bee-higher-kinded-types-c6742e24527

Third article in a series covering Advanced FP in Kotlin / Arrow

Garth Gilmour

@garthgilmour

**Comment by MaureenElsberry** [comment]
Added in #51
