### ISSUE TITLE
Belfast KUG presentation using Arrow

### ISSUE THREAD

**Issue by garthgilmour** [arrow-kt/arrow-media#50]
YouTube video of presentation at KUG

https://www.youtube.com/watch?v=IZlMQXLySz4

Presentation at the January Belfast Kotlin User Group Meetup, covering FP concepts with Arrow

Katie Levy and Shelby Cohen presenting. Garth Gilmour hosting. Also featuring a second talk by Ekaterina Petrova

@klevy110, @shelbyc0hen, @garthgilmour, @KathrinPetrova

**Comment by MaureenElsberry** [comment]
Added in #51
