### ISSUE TITLE
Please add an RSS/Atom feed

### ISSUE THREAD

**Issue by alexandru** [arrow-kt/arrow-media#60]
Would like to keep up to date by following an RSS/Atom feed, but I can't find one.

Adding an RSS feed is fairly easy. You could generate an `atom.xml` yourself (by finding a good template somewhere, let me know if you need help), or you could integrate this plugin: [jekyll-feed](https://github.com/jekyll/jekyll-feed).

**Comment by raulraja** [comment]
@alexandru Thanks for the request 🙏 . We've enabled a feed at https://media.arrow-kt.io/feed.xml. It's good to see you drop by. Cheers!
