### ISSUE TITLE
[Add Media] How to integrate Spring Data Repository with Arrow

### ISSUE THREAD

**Issue by nfrankel** [arrow-kt/arrow-media#63]
**Type of Content:** Blog post

**Link:** https://blog.frankel.ch/custom-spring-data-repository/

**Brief Description of Content:** How to integrate Spring Data Repository with Arrow

**Author/Presenter Name:** Nicolas Fränkel

**Twitter handle:** [@nicolas_frankel](https://twitter.com/nicolas_frankel)

**Comment by MaureenElsberry** [comment]
Thanks @nfrankel! We'll get this added for you!

**Comment by MaureenElsberry** [comment]
Completed in #64
