### ISSUE TITLE
[Add Media] Add talk about eithers/lenses

### ISSUE THREAD

**Issue by vandeven** [arrow-kt/arrow-media#67]
**Type of Content:** videos

**Link:** https://www.youtube.com/watch?v=Wojgv2MeMGU

**Brief Description of Content:** A talk by Ties van de Ven explaining how to use the Either monad in practice and how to use Arrow Optics lenses

**Author/Presenter Name:** Ties van de Ven

**Twitter handle:** ties_ven

```
---
title: Functional programming in Kotlin: Exploring Arrow
header-image: https://img.youtube.com/vi/Wojgv2MeMGU/maxresdefault.jpg

category: videos
tags: [core, optics]
link: https://www.youtub*e.com/watch?v=Wojgv2MeMGU*
event: Kotlin dev days, Amsterdam
---
A talk by Ties van de Ven explaining how to use the Either monad in practice and how to use Arrow Optics lenses

```

**Comment by MaureenElsberry** [comment]
Thanks, @vandeven! - added via #68
